name: Build and Deploy
on:
  push:
    paths: ["soruce/**", ".github/workflows/deploy.yml", "_config.yml"]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: borales/actions-yarn@v2.0.0
        env:
          NODE_ENV: production
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public